@host = http://localhost:3003
# @host = https://tree-simple-server.up.railway.app
@authToken = Bearer {{login.response.body.apiMessage.accessToken}}

###
# @name login
POST {{host}}/user/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345"
}

### get all users
GET {{host}}/user
Authorization: {{authToken}}

###
# create new user
POST  {{host}}/user/signup
Content-Type: application/json

{
  "name": "test2",
  "email": "test2@test.com",
  "password": "12345",
  "role": "student"
}

### remove user
DELETE {{host}}/user
Content-Type: application/json
Authorization: {{authToken}}

{
  "id": "d8b2bb3a-bb88-4ef9-97c7-b9e67c462f04"
}

### update user
PUT {{host}}/user
Content-Type: application/json
Authorization: {{authToken}}

{
  "id": "49ab9b24-93f5-424f-a335-c55e4d5eb4c1",
  "name": "user renamed by put request"
}

### get all groups
GET {{host}}/group
Authorization: {{authToken}}

### get group by id
GET {{host}}/group/id
Content-Type: application/json
Authorization: {{authToken}}

{
  "id": 6
}

### create new group for the logged user
POST  {{host}}/group
Content-Type: application/json
Authorization: {{authToken}}

{
 "name": "this is a group test with req.user.id"
}


### remove group
DELETE {{host}}/group
Content-Type: application/json
Authorization: {{authToken}}

{
  "id": 11
}

### remove people from group
DELETE {{host}}/group/member
Content-Type: application/json
Authorization: {{authToken}}

{
  "groupId": 4,
  "memberId": "396dc9dd-9616-49e1-9dbf-28415d59d357"
}

### add people to group
POST {{host}}/group/member
Content-Type: application/json
Authorization: {{authToken}}

{
  "groupId": 10,
  "memberId": "49ab9b24-93f5-424f-a335-c55e4d5eb4c1"
}

### add sentence for current user
POST {{host}}/sentence
Authorization: {{authToken}}

### get all Sentences from user
GET {{host}}/sentence
Authorization: {{authToken}}


















### DELETE ALL ROWS FROM ALL TABLES
DELETE  {{host}}/management/purge-tables