@host = http://localhost:3003
# @host = https://tree-simple-server.up.railway.app
@authToken = Bearer {{login.response.body.apiMessage.accessToken}}

###
# @name login
POST {{host}}/user/login
Content-Type: application/json

{
  "email": "user-with-group2@test.com",
  "password": "123mudar"
}

### get all users
GET {{host}}/user
Authorization: {{authToken}}

###
# create new user
POST  {{host}}/user
Content-Type: application/json

{
  "name": "user-with-group-2",
  "email": "user-with-group2@test.com",
  "password": "123mudar",
  "role": "student"
}

### remove user
DELETE {{host}}/user
Content-Type: application/json
Authorization: {{authToken}}

{
  "id": "7"
}

### update user
PUT {{host}}/user
Content-Type: application/json
Authorization: {{authToken}}

{
  "id": "9",
  "name": "user renamed by put request"
}

### get all groups
GET {{host}}/group
Authorization: {{authToken}}

### get group by id
GET {{host}}/group/id
Content-Type: application/json
Authorization: {{authToken}}

{
  "id": 2
}

### create new group for the logged user
POST  {{host}}/group
Content-Type: application/json
Authorization: {{authToken}}

{
 "name": "this is a group test with req.user.id"
}


### remove group
DELETE {{host}}/group
Content-Type: application/json
Authorization: {{authToken}}

{
  "id": 2
}

### remove people from group
DELETE {{host}}/group/member
Content-Type: application/json
Authorization: {{authToken}}

{
  "groupId": 4,
  "memberId": "396dc9dd-9616-49e1-9dbf-28415d59d357"
}

### add people to group
POST {{host}}/group/member
Content-Type: application/json
Authorization: {{authToken}}

{
  "groupId": 4,
  "memberId": "d8b2bb3a-bb88-4ef9-97c7-b9e67c462f04"
}

### add